apiVersion: v1
kind: Service
metadata:
  name: claim-initiation-service
  namespace: claim-apps
  labels:
    app: claim-initiation-service
spec:
  selector:
    app: claim-initiation-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP