apiVersion: v1
kind: Service
metadata:
  name: claim-notification-service
  namespace: claim-apps
  labels:
    app: claim-notification-service
spec:
  selector:
    app: claim-notification-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP