name: CI/CD with AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        az-version: latest

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
    - name: Configure kubectl
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
        kubectl config use-context ${{ secrets.AKS_CLUSTER_NAME }}
        
    - name: Deploy to AKS
      run: |
        # Add your deployment commands here
        # For example, you can use kubectl apply to deploy your Kubernetes manifests.
        kubectl apply -f k8s/my-app-deployment.yaml

