server:
  port: 8081
  servlet:
    context-path: /claim/integration

spring:
  mvc:
    problemdeatils:
      enabled: true

logging:
  config: classpath:log4j2.xml

rest:
  url: "https://edldev.shawinc.com/json/FinancialServices"
  username: "svcTDVCMS_NP"
  password: "UALB1ro7kWK4RwVLx1JDH4I%y6Affdav"
  producturl: "https://specifications-np.rhcpnp1.shawinc.com"
  productuuid: "1EF2B5E9-5678-4CD6-8CD7-7DFB0CB4D418"
  dsserviceurl: "https://dsservicessys.rhcpnp1.shawinc.com"
