apiVersion: v1
kind: Service
metadata:
  name: claim-security-service
  namespace: claim-apps
  labels:
    app: claim-security-service
spec:
  selector:
    app: claim-security-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP