apiVersion: v1
kind: Service
metadata:
  name: claim-batch-service
  namespace: claim-apps
  labels:
    app: claim-batch-service
spec:
  selector:
    app: claim-batch-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP